---
title: "Compare conditions"
output: html_notebook
---

 

```{r}
# Read in annotated data
seu <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/testingLibrary/ cluster9000.RDS")

colnames(seu@meta.data)

```


```{r}

# add meta data for all variables wanted to compare
Genotype <- c("3450","3450","3450","AIW002","AIW002","AIW002","AJG001C","AJG001C","AJG001C")
ExDate <- c("0306","0317","0317","0306","0317","0317","0306","0317","0317")
Batch <- c("B","B","A","B","B","A","B","B","A")
Age <- c("273","284","263","273","284","263","273","284","263")

# this could be made into a function later that can take in a list or dataframe

Idents(seu) <- 'Sample'
cluster.ids <-  Batch
names(cluster.ids) <- levels(seu)    # get the levels
seu <- RenameIdents(seu, cluster.ids) # rename  
seu$Batch <- Idents(seu)   # add a new dataslot

Idents(seu) <- 'Sample'
cluster.ids <-  Genotype
names(cluster.ids) <- levels(seu)    # get the levels
seu <- RenameIdents(seu, cluster.ids) # rename  
seu$Genotype <- Idents(seu)   # add a new dataslot

Idents(seu) <- 'Sample'
cluster.ids <-  ExDate
names(cluster.ids) <- levels(seu)    # get the levels
seu <- RenameIdents(seu, cluster.ids) # rename  
seu$ExDate <- Idents(seu)   # add a new dataslot

Idents(seu) <- 'Sample'
cluster.ids <-  Age
names(cluster.ids) <- levels(seu)    # get the levels
seu <- RenameIdents(seu, cluster.ids) # rename  
seu$culturedays <- Idents(seu)   # add a new dataslot

```

Plot proportions of cell types in different conditions

```{r}




```



