---
title: "R Notebook"
output: html_notebook
---

# Figure 3

```{r}
# set up the environment

library(Seurat)
library(dplyr)
library(ggplot2)
library(reshape2)

```


Figure 3A - predicted correlation matrix


```{r}
# Figure 3A 
# Plot the reference matrix for correlation
reference_path <- "/Users/rhalenathomas/GITHUB/CelltypeR/ExampleOuts/FinalReferenceMatrix.csv"
reference_data <- read.csv(reference_path)
# the reference matrix need to be in the format cell types as rows and markers as columns
# there is a column X with the markers
#colnames(reference_data)
# we need a row X with the cell type names
# Transpose the dataframe and convert values to numeric

reference_data <- rbind(reference_data, colnames(reference_data))
rownames(reference_data) <- reference_data$X
reference_data <- reference_data %>% select(-"X")
df_ref <- as.data.frame(t(reference_data))
# make it numeric
df_ref2 <- apply(df_ref, 2, as.numeric)
df_ref2 <- as.data.frame(df_ref2)
# add back the cell type column
df_ref2$X <- df_ref$X
colnames(df_ref2)
rownames(df_ref2) <- df_ref2$X
head(df_ref2)
# Plot the reference matrix


```

Calculate correlations

```{r}

test_path <- "/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outsjan20-9000cells/prepro_outsretrotransformed_flowset.csv"

test.df <- read.csv(test_path)
dim(test.df)
head(test.df)

# with 13 antibodies R value of 0.553 has a significant p value less than 0.05
cor1 <- find_correlation(test = test.df, reference = df_ref,
                        min_corr = 0.553, min_diff = 0.05)
# see how the cells mostly would be assigned if not for the threshold
cor2 <- find_correlation(test = test.df, reference = df_ref,
                        min_corr = 0, min_diff = 0.05)

# threshold for assigning unknown is R < 0.45

# threshold for double label is R1-R2 < 0.05


```

Plot correlations
```{r}
# Figure 3B
# plot the main groups - and the correlation co-efficient for the assigned group
# note  a similar plot is created by the plot_corr function

df <- cor %>% filter(!grepl('-',cell.label))

thresh1 <- 0.45
ggplot(df, aes(x=best.cell.type, y=cor.1, fill = best.cell.type))+ geom_violin(trim = FALSE)+ ylim(0,1)+theme_classic()+
   theme(text = element_text(size = 18), axis.text.x=element_text(angle=90, size = 15)) + ylab("correlation coefficient") + xlab("Cell type with max correlation coefficient") +
  geom_hline(yintercept = thresh1) +
  guides(fill = guide_legend(title = "Cell Phenotype"))

#save this plot for figure 3B
# pdf(paste(output_path,"Vln.max.cor.main.cells.pdf"),height = 4, width = 6)
# ggplot(df, aes(x=best.cell.type, y=cor.1, fill = best.cell.type))+ geom_violin(trim = FALSE)+ ylim(0,1)+theme_classic()+
#    theme(text = element_text(size = 15), axis.text.x=element_text(angle=90, size = 12)) + ylab("correlation coefficient") + xlab("Cell type with max correlation coefficient") +
#   geom_hline(yintercept = thresh1) +
#   guides(fill = guide_legend(title = "Cell Phenotype"))
# dev.off()


# Figure 3 C - bar chart of the frequency of assigned cell types with cut-off freq 400
## remove the unknown cell types
df <- cor
df.filter <- df %>% filter(!grepl('unknown',cell.label))
# filter for only frequent double cell types
df.filter <- df.filter %>% group_by(cell.label) %>% dplyr::filter(n()> 500)

plot1 <- ggplot(df.filter, aes(x=reorder(cell.label,cell.label,function(x)-length(x)), fill = cell.label))+ geom_bar()+theme_classic() +
   theme(text = element_text(size = 16), axis.text.x=element_text(angle=90, hjust = 1))+ xlab('Assigned cell type') + ylab('Number of cells') +
    guides(fill = guide_legend(title = "Cell Phenotype")) 

plot1


plot_corr(cor)
# pdf(paste(output_path,"BarFreq.known400plus.pdf",sep=""),width =6, height = 4)
#   plot1
# dev.off()

```





Figure 3 clustering

This is with the subsample of 9000 cells per hMO
Figure 3D and E

```{r}
# read in the seurat objects
seu <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outsjan20-9000cells/Figure3/cluster_parameters/retro-louv-moreparm/retrotransLouvainSeuratObject60.Rds")
AB <- c("CD24","CD56","CD71","CD29","CD15", "CD184","CD133", "GLAST","CD44","AQP4","HepaCAM","CD140a", "O4" )


# the highest Rand Index are res = 0.1, 7 clusters, res = 0.15, 9 clusters.  Both very low RI std.
# the high RI with low std is 0.3 and 0.7, cluster numbers also have low std 
# from bootstrap 100X
# annotation is easier with 18-25 clusters 

# seu <- RunUMAP(seu,spread = 1, min.dist = 0.05, dims = 1:12)

DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'RNA_snn_res.0.7', repel = TRUE)



# annotate cells 
Idents(seu) <- "RNA_snn_res.0.7"
cluster.ids <- c("LowLabel","Neuron-Glia","Neurons1","RG1","Epi1","Epi-Astro","Neu-OPC","RG-Astro",
                 "Astro","Astro-m","Neurons2","Mix-early-Neu","RG2","RG3","endo","oligo","stem-epi","stem",
                 "neuralstem")

names(cluster.ids) <- levels(seu)
seu <- RenameIdents(seu, cluster.ids)
seu$labels <- Idents(seu)


# with more subgroups

Idents(seu) <- "RNA_snn_res.0.7"
cluster.ids <- c("Unknown","Mixed","Neurons 1","Radial Glia 1","Epithelial","Astrocytes 1","Neurons 2","Astrocytes 1",
                 "Astrocytes 1","Astrocytes 2","Neurons 2","NPC","Radial Glia 2",
                 "Radial Glia 2","Endothelial","Oligodendrocytes","Stem cell like","Stem cell like",
                 "Stem cell like")

names(cluster.ids) <- levels(seu)
seu <- RenameIdents(seu, cluster.ids)
seu$cell.types <- Idents(seu)

DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'cell.types', repel = TRUE)
# there are 13 levels in the cell type annatotion with major groups

# change the order of the cell types on the legend of the umap
cell.type.order <- c("Astrocytes 1", "Astrocytes 2","Radial Glia 1","Radial Glia 2",
                     "Epithelial","Endothelial","NPC","Neurons 1","Neurons 2",
                     "Oligodendrocytes","Stem cell like","Mixed","Unknown")
cell.type.order <- rev(cell.type.order)

# colour order to match cell type order
clust.colours <- c("chocolate1","orange","lightsalmon", "pink",
                   "steelblue3","deepskyblue","plum3","purple","orchid2",
                   "seagreen3","tomato3","burlywood3","grey90")
                   
                   
 #                  "plum1","purple","magenta3","mediumpurple1","darkorchid","plum3",
#             "steelblue3","darkorange1","orange1","lightcoral","coral1","orangered1","lightsalmon",
 #            "cyan")

# Figure 3D UMAP with annotated clusters

# use PDF for figure for correct resolution
# pdf(paste(output_path,"UMAPlabelled9000.08072022.noraster.pdf"),width = 10, height = 5)
# DimPlot(seu, order = cell.type.order, cols = clust.colours, shuffle = TRUE, raster=FALSE,pt.size = 0.1, label = FALSE) +
#   theme(legend.text = element_text(size=24), axis.title.y = element_text(size=24), 
#         axis.title.x = element_text(size=24), axis.text.y = element_text(size =24),
#         axis.text.x = element_text(size =24))
# dev.off()

DimPlot(seu, order = cell.type.order, cols = clust.colours, shuffle = TRUE, raster=FALSE,pt.size = 0.1, label = TRUE)

######## figure 3E heatmap of the 

# reorder the bars to match the UMAP
levels(seu) <- c("Astrocytes 1", "Astrocytes 2","Radial Glia 1","Radial Glia 2",
                     "Epithelial","Endothelial","NPC","Neurons 1","Neurons 2",
                     "Oligodendrocytes","Stem cell like","Mixed","Unknown")

#pdf(paste(output_path,"HM9000.08072022.pdf"),width = 8, height = 5)
DoHeatmap(seu, features = AB, size= 6,slot = "scale.data", group.colors = clust.colours, disp.max = 2, disp.min = -1.5,
          angle = 90) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 15))
#dev.off()


```







