---
title: "Figure 5 hyper gate"
output: html_notebook
---


Read in the annotated dataset


```{r}

library(Seurat)
library(tidyverse)
library(CelltypeR)
library(hypergate)




```

```{r}
seu <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/NatMethodJuneSubmission/Figure4/All9MOannaoteAug.RDS") 
```


Add annotations with main groups of cell types for gating

```{r}
Idents(seu) <- "Celltypes"
levels(seu)

```


```{r}

new.ids <- c("Astrocytes", "Astrocytes", "RadialGlia", "RadialGlia", "RadialGlia", "RadialGlia", "Glia-lineage",
             "Epithelial", "Endothelial", "Neurons1", "Neurons2", "NPC", "Neural-lineage", "Oligodendrocytes",
             "OPC", "OPC-like", "Stemlike")

seu <- annotate(seu, annotations = new.ids, 
                  to_label= "Celltypes", 
                  annotation_name = "GatingCells")

table(seu$GatingCells)

```


```{r}
DimPlot(seu, group.by = "GatingCells", raster = FALSE, label = TRUE)
```




Run hypergate

```{r}

# set the identity to the labels to by the hypergate input
Idents(seu) <- 'GatingCells'

# down sample
i = 2000
# repeat again with new subsample
i = 800
set.seed(i)
seu.down <- subset(x= seu, downsample = i)
DimPlot(seu.down, label = TRUE)
table(seu.down$GatingCells)

# create a matrix to be the input for hypergate
input.xm = as.matrix(GetAssayData(seu.down, slot = 'data'))
xm.t <- t(input.xm)
cluster.labels <- as.vector(seu.down$GatingCells)




```

Run hypergate

```{r}

# make a vector of all the cells to gate

# first I will gate with all cell types
# the number of cells included will alter the gates

cell.types <- c("Astrocytes",  "RadialGlia", "Glia-lineage",
             "Epithelial", "Endothelial", "Neurons1", "Neurons2", "NPC", "Neural-lineage", "Oligodendrocytes",
             "OPC", "OPC-like", "Stemlike")

# run gating and get the output
for (cell in cell.types) {
  hg_output <- hypergate(xp = xm.t, gate_vector = cluster.labels, level = cell)
  gating_predicted = subset_matrix_hg(hg_output,xm.t)
  conf.table <- table(ifelse(gating_predicted, "Gated-in", "Gated-out"), ifelse(cluster.labels ==  cell, cell, "Others"))
  print(cell)
  print(conf.table)
  print(hgate_rule(hg_output))
 
}




```


New subsample with 800 cells

```{r}

cell.types <- c("Astrocytes",  "RadialGlia", "Glia-lineage",
             "Epithelial", "Endothelial", "Neurons1", "Neurons2", "NPC", "Neural-lineage", "Oligodendrocytes",
             "OPC", "OPC-like", "Stemlike")

# run gating and get the output
for (cell in cell.types) {
  hg_output <- hypergate(xp = xm.t, gate_vector = cluster.labels, level = cell)
  gating_predicted = subset_matrix_hg(hg_output,xm.t)
  conf.table <- table(ifelse(gating_predicted, "Gated-in", "Gated-out"), ifelse(cluster.labels ==  cell, cell, "Others"))
  print(cell)
  print(conf.table)
  print(hgate_rule(hg_output))
 
}




```



